import { ArrowLeft, FileSearch, Scale, Upload } from 'lucide-react';

export type ContractReport = { filename: string; overall_risk: string; llm_enhanced: boolean; findings: { rule_id: string; risk_level: string; clause_excerpt: string; explanation: string; suggestion: string; sources: { title: string; provision: string; url: string }[] }[]; disclaimer: string };

export function ContractReview({ lang, report, loading, error, onBack, onReview }: { lang: 'zh' | 'en'; report: ContractReport | null; loading: boolean; error: string; onBack: () => void; onReview: (file: File) => void }) {
  const cn = lang === 'zh';
  return <main className="contract-review"><button className="secondary library-back" onClick={onBack}><ArrowLeft/>{cn ? '返回规划' : 'Back to planner'}</button><div className="eyebrow"><Scale/>{cn ? '租赁合同核验 Skill' : 'Rental contract review skill'}</div><h1>{cn ? '先找规则风险，再解释为什么' : 'Rules first. Explanation second.'}</h1><p className="contract-intro">{cn ? '上传 PDF、TXT 或 Markdown。系统不会保存合同正文，只保存文件哈希和风险报告。扫描版 PDF 暂不支持 OCR。' : 'Upload PDF, TXT or Markdown. Contract text is not stored; only its hash and risk report are retained. Scanned PDFs need OCR first.'}</p>
    <label className="contract-upload"><Upload/><span>{loading ? (cn ? '正在核验…' : 'Reviewing…') : (cn ? '选择合同文件' : 'Choose contract')}</span><input type="file" accept=".pdf,.txt,.md" disabled={loading} onChange={event => { const file = event.target.files?.[0]; if (file) onReview(file); }}/></label>{error && <p className="contract-error">{error}</p>}
    {report && <section className="contract-report"><div className="contract-overall"><FileSearch/><span>{cn ? '总体结果' : 'Overall result'}</span><strong>{report.overall_risk}</strong>{report.llm_enhanced && <em>{cn ? 'AI 证据解释' : 'AI evidence explanation'}</em>}</div>{report.findings.length ? <div className="finding-list">{report.findings.map((finding, index) => <article key={`${finding.rule_id}-${index}`}><span className="risk-level">{finding.risk_level}</span><h2>{finding.clause_excerpt}</h2><p>{finding.explanation}</p><div className="finding-suggestion"><b>{cn ? '建议' : 'Suggestion'}</b>{finding.suggestion}</div><ul>{finding.sources.map(source => <li key={`${finding.rule_id}-${source.url}`}><a href={source.url} target="_blank" rel="noreferrer">{source.title} · {source.provision}</a></li>)}</ul></article>)}</div> : <p>{cn ? '未触发当前预设规则，但仍建议人工核对合同及附件。' : 'No configured rule was triggered; manual review is still recommended.'}</p>}<p className="legal-disclaimer">{report.disclaimer}</p></section>}
  </main>;
}
