import { ArrowLeft, ExternalLink, Heart, History, Trash2 } from 'lucide-react';

export type FavoriteItem = { listing_id: string; listing: { title: string; district: string; neighborhood: string; monthly_rent: number; image_url: string; source_url: string }; created_at: string };
export type HistoryItem = { id: string; request: { city: string; monthly_rent_max: number; destinations: { label: string; address: string }[] }; summary: { total_candidates: number; top_listing_ids: string[] }; provider: string; created_at: string };

export function Library({ view, favorites, history, lang, onBack, onRemoveFavorite }: { view: 'favorites' | 'history'; favorites: FavoriteItem[]; history: HistoryItem[]; lang: 'zh' | 'en'; onBack: () => void; onRemoveFavorite: (listingId: string) => void }) {
  const cn = lang === 'zh';
  return <main className="library"><button className="secondary library-back" onClick={onBack}><ArrowLeft/>{cn ? '返回规划' : 'Back to planner'}</button><div className="eyebrow">{view === 'favorites' ? <Heart/> : <History/>}{view === 'favorites' ? (cn ? '收藏房源' : 'Saved homes') : (cn ? '搜索历史' : 'Search history')}</div><h1>{view === 'favorites' ? (cn ? '你留下的候选房源' : 'Your saved shortlist') : (cn ? '过去的租房方案' : 'Previous rental searches')}</h1>
    {view === 'favorites' ? <div className="library-grid">{favorites.length ? favorites.map(item => <article className="favorite-snapshot" key={item.listing_id}><img src={item.listing.image_url} alt=""/><div><p>{item.listing.district} · {item.listing.neighborhood}</p><h2>{item.listing.title}</h2><strong>¥{item.listing.monthly_rent.toLocaleString()}</strong><small>{cn ? '收藏时快照，当前状态请到原平台确认。' : 'Snapshot when saved; verify current status on source.'}</small><div><a href={item.listing.source_url} target="_blank" rel="noreferrer">{cn ? '查看原平台' : 'Open source'}<ExternalLink/></a><button onClick={() => onRemoveFavorite(item.listing_id)}><Trash2/>{cn ? '移除' : 'Remove'}</button></div></div></article>) : <p>{cn ? '还没有收藏房源。' : 'No saved homes yet.'}</p>}</div> : <div className="history-list">{history.length ? history.map(item => <article key={item.id}><time>{new Date(item.created_at).toLocaleString(cn ? 'zh-CN' : 'en-US')}</time><h2>{item.request.city} · ¥{item.request.monthly_rent_max.toLocaleString()}</h2><p>{item.request.destinations.map(destination => `${destination.label}: ${destination.address}`).join(' · ')}</p><span>{cn ? `${item.summary.total_candidates} 套候选` : `${item.summary.total_candidates} candidates`} · {item.provider}</span></article>) : <p>{cn ? '还没有搜索历史。' : 'No search history yet.'}</p>}</div>}
  </main>;
}
